# Generated by Django 5.1.7 on 2025-03-18 08:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolygonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("poly", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ("antemeridian", models.BooleanField()),
            ],
        ),
    ]
