# Generated by Django 5.1.7 on 2025-03-20 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="polygonmodel",
            name="users",
            field=models.ManyToManyField(
                through="api.UserPolygonModel", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
